"""Shared dataclasses passed between ExfilTrap modules.

The capture module (M1), the traffic generators (M10) and the evaluation
harness (M11) all produce :class:`DNSQuery` records, so the type lives in its
own dependency-free module that every layer can import without pulling in
scapy or scikit-learn.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class DNSQuery:
    """One observed DNS query (M1 live capture or synthetic generator)."""

    src_ip: str
    qname: str
    timestamp: float  # unix epoch seconds (synthetic runs may use t=0-based)


@dataclass(frozen=True)
class LabeledQuery:
    """A DNSQuery plus its ground-truth label, used by training and eval.

    ``is_malicious`` marks queries generated by the tunneling attacker.
    """

    query: DNSQuery
    is_malicious: bool
    meta: dict = field(default_factory=dict)


@dataclass(frozen=True)
class DNSResponse:
    """One observed DNS *response* (the download/C2 channel).

    ``client_ip`` is the response's DESTINATION — the host whose session
    the answer traffic belongs to. ``answer_entropy`` is the Shannon
    entropy of the concatenated answer rdata (encoded C2 payloads score
    near the 5-bit Base32 ceiling; real A/AAAA/CNAME answers are low).
    """

    client_ip: str
    qname: str
    timestamp: float
    answer_count: int
    answer_bytes: int
    answer_entropy: float
